### ISSUE TITLE
Not getting completion for all emmet inputs

### ISSUE THREAD

**Issue by Azeirah** [pedro757/emmet#10]
If I type something like

`#hello` it will give me an emmet autocomplete which correctly expands to `<div id='hello'></div>`

But if I type single elements like

`div`

No expansion options are given at all. As if it doesn't recognize it as an emmet input. This is especially annoying in React where I often want to autocomplete custom tags, which similarly doesn't work `CustomTag` gives me nothing.

I'm using the config in the readme without any changes, using vsnip. I have lsp-config, vsnip, cmp, vsnip-cmp, vsnip-integ and this plugin installed.

**Comment by pedro757** [comment]
Let me check

**Comment by pedro757** [comment]
I think that could be your `cmp` config, maybe you are prioritizing other sources, idk, I just check with `vsnip` and it works

![Peek 2022-02-13 23-27](https://user-images.githubusercontent.com/30637426/153795252-9f98cf55-debf-4423-a244-bf5fea6fd976.gif)

Can you provide a minimal config? including your cmp config.

**Comment by pedro757** [comment]
Still not working?

**Comment by max397574** [comment]
it works for me (with nvim-cmp) so ig it's a problem on his side
