### ISSUE TITLE
php and js

### ISSUE THREAD

**Issue by PablloSC** [pedro757/emmet#13]
how can i make php equal to js and html?

![php](https://user-images.githubusercontent.com/71295978/158310557-789276ee-b16c-4cd5-9ec2-4ae5b0079761.png)
![js](https://user-images.githubusercontent.com/71295978/158310569-7493a591-8393-40d1-840b-5c4a680e8d7d.png)
![html](https://user-images.githubusercontent.com/71295978/158310578-ac81133c-a504-4a33-9d71-48f1201f1726.png)

**Comment by PablloSC** [comment]
![emmet-test](https://user-images.githubusercontent.com/71295978/158936001-38c48cd2-7a16-4a46-b698-8024a9c4ea52.png)

working normally

**Comment by pedro757** [comment]
I added php support for markup emmets.
Run this:
`npm update -g ls_emmet`

Update your config adding php to the filetypes like this
```lua
local lspconfig = require'lspconfig'
local configs = require'lspconfig.configs'

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

if not configs.ls_emmet then
  configs.ls_emmet = {
    default_config = {
      cmd = { 'ls_emmet', '--stdio' };
      filetypes = { "php" };                    --- ADD YOUR LANGUAGES HERE
      root_dir = function(fname)
        return vim.loop.cwd()
      end;
      settings = {};
    };
  }
end

lspconfig.ls_emmet.setup { capabilities = capabilities }
```

**Comment by PablloSC** [comment]
thanks :)
