### ISSUE TITLE
implement tags with classes

### ISSUE THREAD

**Issue by max397574** [pedro757/emmet#2]
implement tags with classes like div.test

**Comment by pedro757** [comment]
I think that's already implemented. but now I see that some completion plugins are not working well with this.

what completion plugin are you using?

**Comment by max397574** [comment]
nvim-cmp

**Comment by max397574** [comment]
from the issue there I came to this repo :)
I used the old emmet ls

**Comment by max397574** [comment]
it looks like it works with one letter only

**Comment by max397574** [comment]
https://user-images.githubusercontent.com/81827001/143278755-cd2aa465-701e-4abb-a2a2-29c236e50a22.mov

**Comment by pedro757** [comment]
This is rare but if you trigger the completion function when you have written the `div.test|` e.g.  in my config it's `<C-space>` it refresh the completion items
![image](https://user-images.githubusercontent.com/30637426/143480380-075b6aaa-db06-4f04-afa0-ae490fb404db.png)


now, I'm trying to solve my debugger **(nvim-dap)** to work with this, so I need some time.

**Comment by max397574** [comment]
any updates @pedro757 ?

**Comment by pedro757** [comment]
I think it's a cmp issue https://github.com/hrsh7th/nvim-cmp/issues/619
But meanwhile you can call the `cmp.complete()` function manually

**Comment by pedro757** [comment]
@max397574 Please update the server `npm update -g ls_emmet` I think it's fixed now.

**Comment by max397574** [comment]
yes is fixed
