### ISSUE TITLE
Cannot access configuration for ls_emmet. Ensure this server is listed in `server_configurations.md` or added as a custom server.

### ISSUE THREAD

**Issue by tin-pham** [pedro757/emmet#3]
I got this bug after I reinstall vim-vsnip due to some bug, now vsnip work  but emmet no long work

![image](https://user-images.githubusercontent.com/20679090/143666252-d34783d4-40fa-4296-8ce7-9580b4a5cebe.png)

**Comment by tin-pham** [comment]
I think i fixed this. I need to load the ls_emmet before tsserver, don't know why but it work now
![image](https://user-images.githubusercontent.com/20679090/143667358-1c37d8c6-2364-4b6b-be88-68b7e605a671.png)

**Comment by pedro757** [comment]
Did you configured the language server as the docs shows? (In the README.md)

**Comment by pedro757** [comment]
Keep in mind that other language servers also have their own snippets so... Make sure my LSP is running with `:LspInfo`

**Comment by tin-pham** [comment]
Thanks for reply. I dont know how but now it work, as I have told above

**Comment by hackorum** [comment]
For anybody who is coming here from the future:
Instead of doing `require'lspconfig/configs'.ls_emmet = {` you need to use `require'lspconfig.configs'.ls_emmet = {`
So, you need to replace the forward slash with a period

**Comment by pedro757** [comment]
What's the difference? @hackorum

**Comment by hackorum** [comment]
I don't know. But that's how me and @tin-pham got it to work

**Comment by pedro757** [comment]
@hackorum that doesn't work for me, `nvim-lspconfig` plugin have been changing some things lately

**Comment by manning390** [comment]
I also had this issue till I found the fix with the period left by hackorum. @pedro757 Perhaps change the readme to use a period rather than a slash if it doesn't make a difference to your configuration.

**Comment by pedro757** [comment]
I'm going to change the slash for a period, it doesn't work for me though. @manning390  u.u

**Comment by pedro757** [comment]
I solved my bug and changed the readme to follow the **nvim-lspconfig** docs, see nvim-lspconfig [breaking chages](https://github.com/neovim/nvim-lspconfig/issues/1075#issuecomment-980801779)
